export const SHOW_LOGIN_MODEL = 'show_login_model'; // jw - 供应商填报 - 新建/编辑供应商
export const SHOW_NEWPRODUCT_MODEL = 'show_NEWPRODUCT_model'; // jw - 供应商填报 - 新建/编辑供应商产品
export const SHOW_FeedBack_MODEL = 'show_FeedBack_model'; // jw - 供应商填报 - 供应商问题反馈
export const SHOW_Choosepsupplier_MODEL = 'show_Choosepsupplier_model'; // jw - 供应商填报 - 选择标准库供应商
export const SHOW_ChooseXzqy_MODEL = 'show_ChooseXzqy_mode'; // jw - 供应商填报 - 选择行政区域
export const SHOW_ChooseCompany_MODEL = 'show_ChooseCompany_model'; // jw - 供应商填报 - 选择院
export const SHOW_SupInfoManager_MODEL = 'show_SupInfoManager_model'; // jw - 供应商基本信息 - 修改供应商信息流程页面
export const SHOW_ProductVerify_MODEL = 'show_ProductVerify_model'; // jw - 核对供应商产品信息 
export const SHOW_Flow_MODEL = 'SHOW_Flow_MODEL'; // jw - 供应商基本信息 - 结束流程页面（审批）
export const SHOW_NEWDIRECT_MODEL = 'show_NewDirectory_model';
export const SHOW_NEWCLASS_MODEL = 'show_NewClass_model';
export const SHOW_SUPINDIRECTORY_MODEL = 'show_SupInDirectory_model';
export const SHOW_CHOOSESUPPLIER_MODEL = 'show_ChooseSupplier_model';
export const SHOW_SupCertificateInfo_MODEL = 'show_SupCertificateInfo_model'; // jw - 供应商资质 - 供应商信息+资质信息
export const SHOW_SupCertificatedetail_MODEL = 'show_SupCertificatedetail_model'; //  jw - 供应商资质 - 资质详细信息
export const SHOW_ChooseRoles_MODEL = 'show_ChooseRoles_model';
export const SHOW_AddBlackList_MODEL = 'show_AddBlackList_model'; // jw - 黑名单 - 将供应商添加至黑名单
export const SHOW_EditSupBaseInfo_MODEL = 'show_EditSupBaseInfo_model';
export const SHOW_GetAuthorizedrole_MODEL = 'show_GetAuthorizedrole_model';
export const SHOW_GetDirectHistory_MODEL = 'show_GetDirectHistory_model';
export const SHOW_RecommendApply_MODEL = 'show_RecommendApply_model';
export const ShOW_RecommendDetail_MODEL = 'show_RecommendDetail_model'; //lzy - 申请详情列表
export const SHOW_PJSSJL_MODEL = 'show_PJSSJL_model'; // jw - 新建评价认定实施记录
export const SHOW_NewBZYQ_MODEL = 'show_NewBZYQ_model'; // jw - 新建标准要求
export const SHOW_NewPJZJ_MODEL = 'show_NewPJZJ_model'; // zdp - 新建评价专家
export const SHOW_NewAGYS_MODEL = 'show_NewAGYS_model'; // zdp - 新建已通过供应商
export const SHOW_NewUNAGYS_MODEL = 'show_NewUNAGYS_model'; // zdp - 新建未通过供应商
export const SHOW_ChooseSupplierPub_MODEL = 'show_ChooseSupplierPub_model'; // jw - 选择供应商公用组件
export const SHOW_NewPJZS_MODEL = 'show_NewPJZS_model'; // jw - 新建评价认定证书
export const SHOW_ShowPJZJ_MODEL = 'show_ShowPJZJ_model'; // lzy - 展示专家详情
export const SHOW_ChooseSpecialist_MODEL = 'show_ChooseSpecialist_model'; // lzy - 展示专家详情
export const SHOW_SupZZApply_MODEL = 'show_SupZZApply_model'; // lzy - 供应商资质申请详情
export const SHOW_SsDetail_MODEL = 'show_SsDetail_model'; // lzy - 供应商资质评价实施记录详情
export const SHOW_ChooseListModel_MODEL = 'show_ChooseListModel_model'; // lzy - 选择列表model
export const SHOW_ShowPJZS_MODEL = 'SHOW_ShowPJZS_MODEL' //lzy - 资质评价证书
export const SHOW_ShowSupApply_MODEL = 'SHOW_ShowSupApply_MODEL'//lzy - 资质评价申请详情
export const SHOW_ShowSupPJrd_MODEL = 'SHOW_ShowSupPJrd_MODEL'//zdp - 供应商评价认定详情
export const SHOW_ShowSupPJrdSS_MODEL = 'SHOW_ShowSupPJrdSS_MODEL'//zdp - 评价中心评价认定详情
export const SHOW_NewSupPJrd_MODEL = 'SHOW_NewSupPJrd_MODEL' // 新建准入认定
export const SHOW_ChooseTBSupperlier_MODEL = 'SHOW_ChooseTBSupperlier_MODEL' //lzy - 选择注册供应商列表
export const SHOW_DirectEdit_MODEL = 'SHOW_DirectEdit_MODEL' //lzy - 名录编辑列表
export const SHOW_DirectorysOfPrevOrg_MODEL = 'SHOW_DirectorysOfPrevOrg_MODEL' //lzy - 获取上级名录列表
export const SHOW_ShowBZkuAdd_MODEL = 'SHOW_ShowBZkuAdd_MODEL' //标准库添加组件
export const SHOW_Process_MODEL = 'SHOW_Process_MODEL' //流程页面组件
export const SHOW_Certificate_MODEL = 'SHOW_Certificate_MODEL' //选择证书组件model
export const SHOW_NewTrainType_MODEL = 'SHOW_NewTrainType_MODEL' ////zq-供应商培训-新建培训类型
export const SHOW_ChooseSpecialistScope_MODEL = 'SHOW_ChooseSpecialistScope_MODEL' ////zq-供应商培训-新建培训类型
export const SHOW_ChooseSuplierScope_MODEL = 'SHOW_ChooseSuplierScope_MODEL' ////zq-供应商培训-新建培训类型
export const SHOW_BlackList_MODEL = 'SHOW_BlackList_MODEL' //nxd-黑名单添加
export const SHOW_EditTrainType_MODEL = 'SHOW_EditTrainType_MODEL' ////zq-供应商培训-新建培训类型
export const SHOW_NewTrainPlan_MODEL = 'SHOW_NewTrainPlan_MODEL' ////zq-供应商培训-新建培训计划
export const SHOW_NewTrainPlot_MODEL = 'SHOW_NewTrainPlot_MODEL' ////zq-供应商培训-新建培训策划
export const SHOW_EditTrainPlan_MODEL = 'SHOW_EditTrainPlan_MODEL' ////zq-供应商培训-编辑培训计划
export const SHOW_ShowArchives_MODEL = 'SHOW_ShowArchives_MODEL' //档案库查询组件
export const SHOW_ModifyBlackList_MODEL = 'SHOW_ModifyBlackList_MODEL' //nxd-黑名单修改
export const SHOW_Modification_MODEL = 'SHOW_Modification_MODEL' //nxd-档案页修改记录查询
export const SHOW_Punishment_MODEL = 'SHOW_Punishment_MODEL' //nxd-档案页惩奖记录详情查询
export const SHOW_TrainLicen_MODEL = 'SHOW_TrainLicen_MODEL' //nxd-资质证书添加页面
export const SHOW_NewPA_MODEL = 'SHOW_NewPA_MODEL' //新建一年一评
export const SHOW_ModelDetail_MODEL = 'SHOW_ModelDetail_MODEL' //查看详情页
export const SHOW_ChooseTrainPlan_MODEL = 'SHOW_ChooseTrainPlan_MODEL' //选择培训计划
export const SHOW_CheckAttachedFiles_MODEL = 'SHOW_CheckAttachedFiles_MODEL' ////zq-查看附件
export const SHOW_ApplyTrain_MODEL = 'SHOW_ApplyTrain_MODEL' ////zq-申请培训
export const SHOW_AddStaff_MODEL = 'SHOW_AddStaff_MODEL' ////zq-申请培训
export const SHOW_TrainApplyDetail_MODEL = 'SHOW_TrainApplyDetail_MODEL' ////zq-查看培训申请详情
export const SHOW_EditContract_MODEL = 'SHOW_EditContract_MODEL' ////zq-查看培训申请详情
export const SHOW_NewReviewPlan_MODEL = 'SHOW_NewReviewPlan_MODEL' //lzy-新建复审计划
export const SHOW_Exposure_MODEL = 'SHOW_Exposure_MODEL' //nxd-曝光台详情
export const SHOW_AddList_MODEL = 'SHOW_AddList_MODEL' //nxd-曝光台新增模块
export const SHOW_Talk_MODEL = 'SHOW_Talk_MODEL' //nxd-投诉回复
export const SHOW_Unit_MODEL = 'SHOW_Unit_MODEL' //nxd-投诉新增上报单位
export const SHOW_addRoot_MODEL = 'SHOW_addRoot_MODEL' //nxd-培训课程新建根目录
export const SHOW_addChildren_MODEL = 'SHOW_addChildren_MODEL' //nxd-培训课程新建子目录
export const SHOW_addTrain_MODEL = 'SHOW_addTrain_MODEL' //nxd-培训课新建课程
export const SHOW_addExpert_MODEL = 'SHOW_addExpert_MODEL' //nxd-培训课添加专家
export const SHOW_uploadCourseware_MODEL = 'SHOW_uploadCourseware_MODEL' //nxd-培训课上传课件
export const SHOW_NoticeDetails_MODEL = 'SHOW_NoticeDetails_MODEL' //nxd-培训通知详情
export const SHOW_NoticeSignUp_MODEL = 'SHOW_NoticeSignUp_MODEL' //nxd-培训报名
export const SHOW_ManualInput_MODEL = 'SHOW_ManualInput_MODEL' //nxd-培训报名手动了录入model
export const SHOW_ListSelection_MODEL = 'SHOW_ListSelection_MODEL' //nxd-培训报名选择model
export const SHOW_SpwcialDetails_MODEL = 'SHOW_SpwcialDetails_MODEL' //nxd-专项培训详情model
export const SHOW_AddAdmittance_MODEL = 'SHOW_AddAdmittance_MODEL' //nxd-准入培训新建model
export const SHOW_Initialization_MODEL = 'SHOW_Initialization_MODEL' //nxd-名录二 初始化供应商
export const SHOW_Restricted_MODEL = 'SHOW_Restricted_MODEL' //nxd-名录二 限用
export const SHOW_Authorization_MODEL = 'SHOW_Authorization_MODEL' //nxd-名录二 授权
export const SHOW_NewGYS_MODEL = 'SHOW_NewGYS_MODEL' //nxd-名录二 查看新增供应商
export const SHOW_GYSDirectories_MODEL = 'SHOW_GYSDirectories_MODEL' //nxd-名录二 供应商名录修改记录
export const SHOW_GYSInformation_MODEL = 'SHOW_GYSInformation_MODEL' //nxd-名录二 供应商基础信息修改记录
export const SHOW_GYSHistory_MODEL = 'SHOW_GYSHistory_MODEL' //nxd-名录二 供应商名录修改记录
export const SHOW_Notice_MODEL = 'SHOW_Notice_MODEL' //nxd-名录二 名录修改通知
export const SHOW_Unexecuted_MODEL = 'SHOW_Unexecuted_MODEL' //nxd-名录二 名录修改未执行单位

export const SHOW_MyRecommendationNewlyAdded_MODEL = 'SHOW_MyRecommendationNewlyAdded_MODEL' //nxd-准入-我的推荐-新增





