

const CHANGE_NUM = 'CHANGE_NUM'
const CHANGE_NUM_ADD = 'CHANGE_NUM_ADD'
const CHANGE_NUM_DELETE = 'CHANGE_NUM_DELETE'
const SETYOGGLE = 'SETYOGGLE'
const ADD_INFO = 'ADD_INFO'
const SHOW_MODAL = 'SHOW_MODAL'

export default {
    CHANGE_NUM,
    CHANGE_NUM_ADD,
    CHANGE_NUM_DELETE,
    SETYOGGLE,
    ADD_INFO,
    SHOW_MODAL
}